import type { FilterPreset, MoodOption } from './types';

export const FILTERS: FilterPreset[] = [
  {
    id: 'natural',
    name: 'Natural',
    mood: 'neutral',
    cssFilter: 'none',
    thumbnailGradient: 'from-slate-600 to-slate-800',
  },
  {
    id: 'soft',
    name: 'Soft',
    mood: 'calm',
    cssFilter: 'brightness(1.08) contrast(0.92) saturate(0.85) blur(0.3px)',
    thumbnailGradient: 'from-rose-300/50 to-amber-200/40',
    beauty: {
      skinSmooth: 0.35,
      brightness: 1.08,
      contrast: 0.92,
      saturation: 0.85,
      warmth: 0.05,
      glow: 0.15,
      vignette: 0,
      blur: 0.3,
    },
  },
  {
    id: 'glow',
    name: 'Glow',
    mood: 'happy',
    cssFilter: 'brightness(1.12) contrast(1.0) saturate(1.1) blur(0.4px)',
    thumbnailGradient: 'from-amber-200/50 to-yellow-300/40',
    beauty: {
      skinSmooth: 0.45,
      brightness: 1.12,
      contrast: 1.0,
      saturation: 1.1,
      warmth: 0.1,
      glow: 0.35,
      vignette: 0,
      blur: 0.4,
    },
  },
  {
    id: 'warm',
    name: 'Warm',
    mood: 'calm',
    cssFilter: 'sepia(0.25) saturate(1.3) brightness(1.05) hue-rotate(-10deg)',
    thumbnailGradient: 'from-amber-400/50 to-orange-500/40',
    beauty: {
      skinSmooth: 0.3,
      brightness: 1.05,
      contrast: 1.05,
      saturation: 1.15,
      warmth: 0.25,
      glow: 0.1,
      vignette: 0.1,
      blur: 0.2,
    },
  },
  {
    id: 'cool',
    name: 'Cool',
    mood: 'neutral',
    cssFilter: 'saturate(0.8) brightness(0.95) hue-rotate(15deg) contrast(1.05)',
    thumbnailGradient: 'from-cyan-400/50 to-blue-500/40',
    beauty: {
      skinSmooth: 0.3,
      brightness: 0.98,
      contrast: 1.05,
      saturation: 0.85,
      warmth: -0.1,
      glow: 0.05,
      vignette: 0.05,
      blur: 0.2,
    },
  },
  {
    id: 'bright',
    name: 'Bright',
    mood: 'energetic',
    cssFilter: 'brightness(1.25) contrast(1.1) saturate(1.2)',
    thumbnailGradient: 'from-yellow-300/60 to-amber-400/50',
    beauty: {
      skinSmooth: 0.4,
      brightness: 1.2,
      contrast: 1.08,
      saturation: 1.2,
      warmth: 0.08,
      glow: 0.25,
      vignette: 0,
      blur: 0.3,
    },
  },
  {
    id: 'cinematic',
    name: 'Cinematic',
    mood: 'neutral',
    cssFilter: 'contrast(1.2) saturate(0.9) brightness(0.95) sepia(0.15)',
    thumbnailGradient: 'from-stone-500/50 to-stone-700/60',
    beauty: {
      skinSmooth: 0.2,
      brightness: 0.95,
      contrast: 1.2,
      saturation: 0.9,
      warmth: 0.12,
      glow: 0,
      vignette: 0.3,
      blur: 0,
    },
  },
  {
    id: 'dreamy',
    name: 'Dreamy',
    mood: 'relaxed',
    cssFilter: 'blur(0.8px) brightness(1.1) saturate(1.15) contrast(0.9)',
    thumbnailGradient: 'from-violet-300/40 to-pink-300/40',
    beauty: {
      skinSmooth: 0.55,
      brightness: 1.1,
      contrast: 0.9,
      saturation: 1.15,
      warmth: 0.08,
      glow: 0.4,
      vignette: 0.15,
      blur: 0.8,
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    mood: 'melancholic',
    cssFilter: 'brightness(0.7) contrast(1.15) saturate(0.75)',
    thumbnailGradient: 'from-gray-700/60 to-gray-900/70',
    beauty: {
      skinSmooth: 0.25,
      brightness: 0.72,
      contrast: 1.15,
      saturation: 0.75,
      warmth: -0.05,
      glow: 0,
      vignette: 0.4,
      blur: 0,
    },
  },
];

export const MOODS: MoodOption[] = [
  { id: 'happy', label: 'Happy', emoji: '😊' },
  { id: 'calm', label: 'Calm', emoji: '😌' },
  { id: 'good', label: 'Good', emoji: '🙂' },
  { id: 'neutral', label: 'Neutral', emoji: '😐' },
  { id: 'tired', label: 'Tired', emoji: '😴' },
  { id: 'sad', label: 'Sad', emoji: '😢' },
  { id: 'anxious', label: 'Anxious', emoji: '😰' },
  { id: 'angry', label: 'Angry', emoji: '😠' },
  { id: 'excited', label: 'Excited', emoji: '🤩' },
];

export const PROCESSING_STATUSES = {
  recorded: { label: 'Saved', color: 'text-amber-400', dot: 'bg-amber-400' },
  transcribing: { label: 'Transcribing', color: 'text-blue-400', dot: 'bg-blue-400' },
  transcribed: { label: 'Transcribed', color: 'text-blue-400', dot: 'bg-blue-400' },
  mood_processed: { label: 'Analyzing mood', color: 'text-blue-400', dot: 'bg-blue-400' },
  cleaning: { label: 'Cleaning up', color: 'text-blue-400', dot: 'bg-blue-400' },
  cleaned: { label: 'Cleaned', color: 'text-blue-400', dot: 'bg-blue-400' },
  sending_to_hindsight: { label: 'Saving to memory', color: 'text-blue-400', dot: 'bg-blue-400' },
  completed: { label: 'Ready', color: 'text-emerald-400', dot: 'bg-emerald-400' },
  error: { label: 'Error', color: 'text-red-400', dot: 'bg-red-400' },
} as const;
